[package]
name = "tcp_noyberg"
version = "0.1.0"
authors = ["student5308"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "0.1"